import pandas as pd


verses_fr_expanded = [
    ("Le Seigneur est mon berger: je ne manquerai de rien.", "Psaume 23:1"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Car je connais les projets que j'ai formés sur vous.", "Jérémie 29:11"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Et déchargez-vous sur lui de tous vos soucis.", "1 Pierre 5:7"),
    ("Le fruit de l'Esprit, c'est l'amour, la joie, la paix.", "Galates 5:22"),
    ("Confie-toi en l'Éternel de tout ton cœur.", "Proverbes 3:5"),
    ("Le nom de l'Éternel est une tour forte.", "Proverbes 18:10"),
    ("L'Éternel est bon, il est un refuge.", "Nahum 1:7"),
    ("Louez l'Éternel, car il est bon.", "Psaume 107:1"),
    ("L'Éternel marchera devant toi, il sera avec toi.", "Deutéronome 31:8"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Fortifie-toi et prends courage!", "Josué 1:9"),
    ("Et mon Dieu pourvoira à tous vos besoins.", "Philippiens 4:19"),
    ("L'Éternel est près de ceux qui l'invoquent.", "Psaume 145:18"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("Nous regardons aux choses invisibles.", "2 Corinthiens 4:18"),
    ("L'Éternel est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("Je t'aime, ô Éternel, ma force!", "Psaume 18:1"),
    ("L'Éternel est mon bouclier, mon puissant soutien.", "Psaume 28:7"),
    ("Car je connais mes transgressions.", "Psaume 51:3"),
    ("Crée en moi un cœur pur, ô Dieu!", "Psaume 51:10"),
    ("Rends-moi la joie de ton salut.", "Psaume 51:12"),
    ("Car Dieu est avec moi.", "Psaume 56:9"),
    ("Mon âme se repose en Dieu seul.", "Psaume 62:1"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("Ne crains point, car je suis avec toi.", "Ésaïe 41:10"),
    ("Le Seigneur, ton Dieu, est au milieu de toi.", "Sophonie 3:17"),
    ("Tu aimeras ton prochain comme toi-même.", "Matthieu 22:39"),
    ("Le ciel et la terre passeront.", "Matthieu 24:35"),
    ("Et voici, je suis avec vous tous les jours.", "Matthieu 28:20"),
    ("Tout ce que vous demanderez avec foi.", "Matthieu 21:22"),
    ("Car là où deux ou trois sont assemblés.", "Matthieu 18:20"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("L'amour est patient, il est plein de bonté.", "1 Corinthiens 13:4"),
    ("Faites tout pour la gloire de Dieu.", "1 Corinthiens 10:31"),
    ("Car nous marchons par la foi.", "2 Corinthiens 5:7"),
    ("Dieu est fidèle, il ne permettra pas.", "1 Corinthiens 10:13"),
    ("Je vous ai dit ces choses, afin que vous ayez la paix.", "Jean 16:33"),
    ("Le Seigneur est proche de tous ceux qui l'invoquent.", "Psaume 145:18"),
    ("C'est en Dieu que mon âme se confie.", "Psaume 62:1"),
    ("L'Éternel est bon, il est un refuge au jour de la détresse.", "Nahum 1:7"),
    ("Louez l'Éternel, car il est bon.", "Psaume 136:1"),
    ("Le Seigneur est mon berger.", "Psaume 23:1"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Nous aimons, car il nous a aimés le premier.", "1 Jean 4:19"),
    ("Vous êtes la lumière du monde.", "Matthieu 5:14"),
    ("Ne vous inquiétez de rien.", "Philippiens 4:6"),
    ("La joie de l'Éternel est votre force.", "Néhémie 8:10"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Nous savons que toutes choses concourent au bien.", "Romains 8:28"),
    ("Je vous laisse la paix, je vous donne ma paix.", "Jean 14:27"),
    ("La foi est une ferme assurance des choses qu'on espère.", "Hébreux 11:1"),
    ("Car Dieu a tant aimé le monde.", "Jean 3:16"),
    ("L'Éternel est bon, il est un refuge au jour de la détresse.", "Nahum 1:7"),
    ("Car la parole de Dieu est vivante et efficace.", "Hébreux 4:12"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Car il a été transpercé pour nos péchés.", "Ésaïe 53:5"),
    ("L'Éternel est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Nous savons que toutes choses concourent au bien.", "Romains 8:28"),
    ("Car Dieu a tant aimé le monde.", "Jean 3:16"),
    ("Le Seigneur est mon berger: je ne manquerai de rien.", "Psaume 23:1"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("L'Éternel est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("Car Dieu a tant aimé le monde.", "Jean 3:16"),
    ("Car nous marchons par la foi.", "2 Corinthiens 5:7"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("Tout ce que vous demanderez avec foi.", "Matthieu 21:22"),
    ("L'Éternel est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("Car il a été transpercé pour nos péchés.", "Ésaïe 53:5"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("Car la parole de Dieu est vivante et efficace.", "Hébreux 4:12"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("Tout ce que vous demanderez avec foi.", "Matthieu 21:22"),
    ("L'Éternel est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("Car Dieu a tant aimé le monde.", "Jean 3:16"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("manquerai de rien.", "Psaume 23:1"),
    ("Car vous êtes tous fils de Dieu par la foi.", "Galates 3:26"),
    ("Restez en paix avec tous les hommes.", "Romains 12:18"),
    ("Il n'y a pas de crainte dans l'amour.", "1 Jean 4:18"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est mon berger, je ne manquerai de rien.", "Psaume 23:1"),
    ("Je suis la lumière du monde.", "Jean 8:12"),
    ("Recherchez d'abord son royaume et sa justice.", "Matthieu 6:33"),
    ("Le Seigneur est ma force et mon bouclier.", "Psaume 28:7"),
    ("Car tous ont péché et sont privés de la gloire de Dieu.", "Romains 3:23"),
    ("Dieu est amour.", "1 Jean 4:8"),
    ("Le Seigneur est bon, il est un refuge au jour de la détresse.", "Nahum 1:7"),
    ("Louez l'Éternel, car il est bon, car sa miséricorde dure à jamais.", "Psaume 107:1"),
    ("Que tout ce qui respire loue l'Éternel!", "Psaume 150:6"),
    ("Ta parole est la vérité.", "Jean 17:17"),
    ("Il y a un seul Dieu, un seul médiateur entre Dieu et les hommes.", "1 Timothée 2:5"),
    ("Dieu est lumière, et il n'y a point en lui de ténèbres.", "1 Jean 1:5"),
    ("Je vous laisse la paix, je vous donne ma paix.", "Jean 14:27"),
    ("Le Seigneur est près de tous ceux qui l'invoquent.", "Psaume 145:18"),
    ("Le Seigneur est ma lumière et mon salut.", "Psaume 27:1"),
    ("Il est mon rocher et mon salut.", "Psaume 62:2"),
    ("Je suis l'alpha et l'oméga.", "Apocalypse 22:13"),
    ("Que votre amour augmente de plus en plus.", "Philippiens 1:9"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("Que le Dieu de l'espérance vous remplisse de toute joie.", "Romains 15:13"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Je vous ai aimés d'un amour éternel.", "Jérémie 31:3"),
    ("Je suis avec vous tous les jours.", "Matthieu 28:20"),
    ("Le Seigneur est ma lumière et mon salut.", "Psaume 27:1"),
    ("La joie de l'Éternel est votre force.", "Néhémie 8:10"),
    ("Nous savons que toutes choses concourent au bien.", "Romains 8:28"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Il est ma lumière et mon salut.", "Psaume 27:1"),
    ("Le Seigneur est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("Confie-toi en l'Éternel de tout ton cœur.", "Proverbes 3:5"),
    ("Crée en moi un cœur pur, ô Dieu!", "Psaume 51:10"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Dieu est amour.", "1 Jean 4:8"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("L'amour est patient, il est plein de bonté.", "1 Corinthiens 13:4"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("Dieu est notre refuge et notre force.", "Psaume 46:1"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est ma lumière et mon salut.", "Psaume 27:1"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est mon berger, je ne manquerai de rien.", "Psaume 23:1"),
    ("Je suis la lumière du monde.", "Jean 8:12"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("Le Seigneur est ma force et mon bouclier.", "Psaume 28:7"),
    ("Dieu est fidèle, il ne permettra pas que vous soyez tentés au-delà de vos forces.", "1 Corinthiens 10:13"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Ne crains point, car je suis avec toi.", "Ésaïe 41:10"),
    ("Le Seigneur est proche de tous ceux qui l'invoquent.", "Psaume 145:18"),
    ("Nous marchons par la foi, et non par la vue.", "2 Corinthiens 5:7"),
    ("Le Seigneur est bon, il est un refuge au jour de la détresse.", "Nahum 1:7"),
    ("Je vous laisse la paix, je vous donne ma paix.", "Jean 14:27"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("Dieu est notre refuge et notre force.", "Psaume 46:1"),
    ("Je suis l'alpha et l'oméga, le commencement et la fin.", "Apocalypse 22:13"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Je vous ai dit ces choses, afin que vous ayez la paix.", "Jean 16:33"),
    ("Nous aimons, car il nous a aimés le premier.", "1 Jean 4:19"),
    ("Car Dieu a tant aimé le monde.", "Jean 3:16"),
    ("Le Seigneur est mon berger, je ne manquerai de rien.", "Psaume 23:1"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("Le Seigneur est proche de tous ceux qui l'invoquent.", "Psaume 145:18"),
    ("Crée en moi un cœur pur, ô Dieu!", "Psaume 51:10"),
    ("Je suis la lumière du monde.", "Jean 8:12"),
    ("L'amour est patient, il est plein de bonté.", "1 Corinthiens 13:4"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("Le Seigneur est mon berger, je ne manquerai de rien.", "Psaume 23:1"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("Le Seigneur est mon rocher, ma forteresse.", "Psaume 18:2"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Cherchez premièrement le royaume de Dieu.", "Matthieu 6:33"),
    ("L'Éternel est mon bouclier, il est ma force.", "Psaume 28:7"),
    ("L'amour est patient, il est plein de bonté.", "1 Corinthiens 13:4"),
    ("Dieu est fidèle, il ne permettra pas que vous soyez tentés au-delà de vos forces.", "1 Corinthiens 10:13"),
    ("Que le Dieu de l'espérance vous remplisse de toute joie.", "Romains 15:13"),
    ("Nous savons que toutes choses concourent au bien de ceux qui aiment Dieu.", "Romains 8:28"),
    ("Le Seigneur est ma force et mon bouclier.", "Psaume 28:7"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Le Seigneur est ma lumière et mon salut.", "Psaume 27:1"),
    ("Dieu est amour.", "1 Jean 4:8"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Cherchez premièrement le royaume de Dieu et sa justice.", "Matthieu 6:33"),
    ("Le Seigneur est mon berger: je ne manquerai de rien.", "Psaume 23:1"),
    ("L'Éternel est bon pour tous.", "Psaume 145:9"),
    ("L'amour couvre une multitude de péchés.", "1 Pierre 4:8"),
    ("Ne crains rien, car je suis avec toi.", "Ésaïe 41:10"),
    ("Il est notre paix.", "Éphésiens 2:14"),
    ("Nous marchons par la foi, non par la vue.", "2 Corinthiens 5:7"),
    ("Le Seigneur est mon rocher, ma forteresse, mon libérateur.", "Psaume 18:2"),
    ("Je vous ai dit ces choses, afin que vous ayez la paix.", "Jean 16:33"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("L'Éternel est ma force et mon chant.", "Psaume 118:14"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Je suis la lumière du monde.", "Jean 8:12"),
    ("L'amour est patient, il est plein de bonté.", "1 Corinthiens 13:4"),
    ("Que votre cœur ne se trouble point.", "Jean 14:1"),
    ("Le Seigneur est proche de tous ceux qui l'invoquent.", "Psaume 145:18"),
    ("Je suis le pain de vie.", "Jean 6:35"),
    ("Le Seigneur est mon berger, je ne manquerai de rien.", "Psaume 23:1"),
    ("Dieu est fidèle.", "1 Corinthiens 1:9"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est mon refuge.", "Psaume 91:2"),
    ("Il est notre paix.", "Éphésiens 2:14"),
    ("Dieu est fidèle.", "1 Corinthiens 1:9"),
    ("L'Éternel est ma lumière et mon salut.", "Psaume 27:1"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Je suis le chemin, la vérité et la vie.", "Jean 14:6"),
    ("L'Éternel est bon, sa miséricorde dure à toujours.", "Psaume 136:1"),
    ("Dieu est amour.", "1 Jean 4:8"),
    ("Je suis la résurrection et la vie.", "Jean 11:25"),
    ("Ta parole est une lampe à mes pieds.", "Psaume 119:105"),
    ("Dieu est fidèle.", "1 Corinthiens 1:9"),
    ("Je puis tout par celui qui me fortifie.", "Philippiens 4:13"),
    ("Le Seigneur est mon refuge.", "Psaume 91:2")
]

# Créer un DataFrame avec les versets bibliques
df = pd.DataFrame(verses_fr_expanded, columns=["Verset", "Référence"])

# Sauvegarder le DataFrame dans un fichier Excel
df.to_excel("versets_bibliques_fr.xlsx", index=False)

print("Le fichier Excel a été créé avec succès!")
